In [50]:
import pandas as pd 
import numpy as np 
import requests 
from bs4 import BeautifulSoup, Comment
from io import StringIO

In [51]:
url = "https://www.basketball-reference.com/leagues/NBA_2025.html#all_all_awards"

In [52]:
r = requests.get(url)

print(r.status_code == 200)

True

In [53]:
soup = BeautifulSoup(r.content, "html.parser")
wrapper = soup.find("div", id="all_all_awards")

table_comment = wrapper.find(
    string=lambda text: isinstance(text, Comment)
    and 'id="all_awards"' in text
)

table_soup = BeautifulSoup(table_comment, "html.parser")
table = table_soup.find("table", id="all_awards")

In [54]:
raw_df = pd.read_html(StringIO(str(table)))[0]

In [55]:
raw_df

                                               Award                   Winner
0       Most Valuable Player (Michael Jordan Trophy)  Shai Gilgeous-Alexander
1       Rookie of the Year (Wilt Chamberlain Trophy)           Stephon Castle
2  Defensive Player of the Year (Hakeem Olajuwon ...              Evan Mobley
3         Most Improved Player (George Mikan Trophy)            Dyson Daniels
4       Sixth Man of the Year (John Havlicek Trophy)         Payton Pritchard
5          In-Season Tournament Most Valuable Player    Giannis Antetokounmpo
6      Clutch Player of the Year (Jerry West Trophy)            Jalen Brunson
7                                   NBA Hustle Award           Draymond Green

In [56]:
raw_df["Alternate Award Name"] = raw_df["Award"].str.split("(").str[1].str.split(")").str[0]
raw_df["Alternate Award Name"] = raw_df["Alternate Award Name"].fillna("None")

In [57]:
raw_df["Award"] = raw_df["Award"].str.split("(").str[0].str.strip()

In [58]:
raw_df

,Award,Winner,Alternate Award Name
0,Most Valuable Player,Shai Gilgeous-Alexander,Michael Jordan Trophy
1,Rookie of the Year,Stephon Castle,Wilt Chamberlain Trophy
2,Defensive Player of the Year,Evan Mobley,Hakeem Olajuwon Trophy
3,Most Improved Player,Dyson Daniels,George Mikan Trophy
4,Sixth Man of the Year,Payton Pritchard,John Havlicek Trophy
5,In-Season Tournament Most Valuable Player,Giannis Antetokounmpo,None
6,Clutch Player of the Year,Jalen Brunson,Jerry West Trophy
7,NBA Hustle Award,Draymond Green,None

In [59]:
wrapper = soup.find("div", id="all_all-nba")
all_nba_comment = wrapper.find(
    string = lambda text: isinstance(text, Comment)
    and 'id="div_all-nba"' in text
)

all_nba_soup = BeautifulSoup(all_nba_comment, "html.parser")
all_nba_div = all_nba_soup.find("div", id="div_all-nba")

In [60]:
first_team = all_nba_div.find("div", id="all-nba_1")
second_team = all_nba_div.find("div", id="all-nba_2")
third_team = all_nba_div.find("div", id="all-nba_3")

In [61]:
data = {"player" : [], "accolade" : []}

for x in first_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("1st Team All-NBA")

for x in second_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("2nd Team All-NBA")

for x in third_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("3rd Team All-NBA")

In [62]:
wrapper = soup.find("div", id="all_all-defensive")
all_nba_comment = wrapper.find(
    string = lambda text: isinstance(text, Comment)
    and 'id="div_all-defensive"' in text
)

all_nba_soup = BeautifulSoup(all_nba_comment, "html.parser")
all_nba_div = all_nba_soup.find("div", id="div_all-defensive")

first_team = all_nba_div.find("div", id="all-defensive_1")
second_team = all_nba_div.find("div", id="all-defensive_2")

for x in first_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("1st Team All-Defensive")

for x in second_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("2nd Team All-Defensive")

In [63]:
wrapper = soup.find("div", id="all_all-rookie")
all_nba_comment = wrapper.find(
    string = lambda text: isinstance(text, Comment)
    and 'id="div_all-rookie"' in text
)

all_nba_soup = BeautifulSoup(all_nba_comment, "html.parser")
all_nba_div = all_nba_soup.find("div", id="div_all-rookie")

first_team = all_nba_div.find("div", id="all-rookie_1")
second_team = all_nba_div.find("div", id="all-rookie_2")

for x in first_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("1st Team All-Rookie")

for x in second_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("2nd Team All-Rookie")

In [64]:
wrapper = soup.find("div", id="all_in-seasontournamentall-tournamentteam")
all_nba_comment = wrapper.find(
    string = lambda text: isinstance(text, Comment)
    and 'id="div_in-seasontournamentall-tournamentteam"' in text
)

all_nba_soup = BeautifulSoup(all_nba_comment, "html.parser")
all_nba_div = all_nba_soup.find("div", id="div_in-seasontournamentall-tournamentteam")

first_team = all_nba_div.find("div", id="in-seasontournamentall-tournamentteam_1")

for x in first_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("1st Team In-Season Tournament All-Tournament")

In [65]:
pd.DataFrame(data)

                       player                                      accolade
0      Giannis Antetokounmpo                               1st Team All-NBA
1    Shai Gilgeous-Alexander                               1st Team All-NBA
2               Nikola Jokić                               1st Team All-NBA
3           Donovan Mitchell                               1st Team All-NBA
4               Jayson Tatum                               1st Team All-NBA
5              Jalen Brunson                               2nd Team All-NBA
6              Stephen Curry                               2nd Team All-NBA
7            Anthony Edwards                               2nd Team All-NBA
8               LeBron James                               2nd Team All-NBA
9                Evan Mobley                               2nd Team All-NBA
10           Cade Cunningham                               3rd Team All-NBA
11         Tyrese Haliburton                               3rd Team All-NBA
12              James Harden                               3rd Team All-NBA
13        Karl-Anthony Towns                               3rd Team All-NBA
14            Jalen Williams                               3rd Team All-NBA
15             Dyson Daniels                         1st Team All-Defensive
16             Luguentz Dort                         1st Team All-Defensive
17            Draymond Green                         1st Team All-Defensive
18               Evan Mobley                         1st Team All-Defensive
19             Amen Thompson                         1st Team All-Defensive
20            Toumani Camara                         2nd Team All-Defensive
21               Rudy Gobert                         2nd Team All-Defensive
22         Jaren Jackson Jr.                         2nd Team All-Defensive
23            Jalen Williams                         2nd Team All-Defensive
24               Ivica Zubac                         2nd Team All-Defensive
25            Stephon Castle                            1st Team All-Rookie
26                 Zach Edey                            1st Team All-Rookie
27        Zaccharie Risacher                            1st Team All-Rookie
28                 Alex Sarr                            1st Team All-Rookie
29              Jaylen Wells                            1st Team All-Rookie
30             Matas Buzelis                            2nd Team All-Rookie
31            Bub Carrington                            2nd Team All-Rookie
32           Donovan Clingan                            2nd Team All-Rookie
33                Yves Missi                            2nd Team All-Rookie
34               Kel'el Ware                            2nd Team All-Rookie
35     Giannis Antetokounmpo   1st Team In-Season Tournament All-Tournament
36   Shai Gilgeous-Alexander   1st Team In-Season Tournament All-Tournament
37            Damian Lillard   1st Team In-Season Tournament All-Tournament
38            Alperen Şengün   1st Team In-Season Tournament All-Tournament
39                Trae Young   1st Team In-Season Tournament All-Tournament

In [66]:
wrapper = soup.find("div", id="all_all_star_game_rosters")
all_nba_comment = wrapper.find(
    string = lambda text: isinstance(text, Comment)
    and 'id="div_all_star_game_rosters"' in text
)

all_nba_soup = BeautifulSoup(all_nba_comment, "html.parser")
all_nba_div = all_nba_soup.find("div", id="div_all_star_game_rosters")

first_team = all_nba_div.find("div", id="all_star_game_rosters_1")
second_team = all_nba_div.find("div", id="all_star_game_rosters_2")
third_team = all_nba_div.find("div", id="all_star_game_rosters_3")

for x in first_team.find_all("p") + second_team.find_all("p") + third_team.find_all("p"):
    data["player"].append(x.text)
    data["accolade"].append("NBA All-Star")

In [68]:
awards = pd.DataFrame(data)
awards["player"] = awards.player.str.split("(").str[0].str.strip()

In [69]:
pd.set_option("display.max_rows", None)
awards

                     player                                      accolade
0     Giannis Antetokounmpo                              1st Team All-NBA
1   Shai Gilgeous-Alexander                              1st Team All-NBA
2              Nikola Jokić                              1st Team All-NBA
3          Donovan Mitchell                              1st Team All-NBA
4              Jayson Tatum                              1st Team All-NBA
5             Jalen Brunson                              2nd Team All-NBA
6             Stephen Curry                              2nd Team All-NBA
7           Anthony Edwards                              2nd Team All-NBA
8              LeBron James                              2nd Team All-NBA
9               Evan Mobley                              2nd Team All-NBA
10          Cade Cunningham                              3rd Team All-NBA
11        Tyrese Haliburton                              3rd Team All-NBA
12             James Harden                              3rd Team All-NBA
13       Karl-Anthony Towns                              3rd Team All-NBA
14           Jalen Williams                              3rd Team All-NBA
15            Dyson Daniels                        1st Team All-Defensive
16            Luguentz Dort                        1st Team All-Defensive
17           Draymond Green                        1st Team All-Defensive
18              Evan Mobley                        1st Team All-Defensive
19            Amen Thompson                        1st Team All-Defensive
20           Toumani Camara                        2nd Team All-Defensive
21              Rudy Gobert                        2nd Team All-Defensive
22        Jaren Jackson Jr.                        2nd Team All-Defensive
23           Jalen Williams                        2nd Team All-Defensive
24              Ivica Zubac                        2nd Team All-Defensive
25           Stephon Castle                           1st Team All-Rookie
26                Zach Edey                           1st Team All-Rookie
27       Zaccharie Risacher                           1st Team All-Rookie
28                Alex Sarr                           1st Team All-Rookie
29             Jaylen Wells                           1st Team All-Rookie
30            Matas Buzelis                           2nd Team All-Rookie
31           Bub Carrington                           2nd Team All-Rookie
32          Donovan Clingan                           2nd Team All-Rookie
33               Yves Missi                           2nd Team All-Rookie
34              Kel'el Ware                           2nd Team All-Rookie
35    Giannis Antetokounmpo  1st Team In-Season Tournament All-Tournament
36  Shai Gilgeous-Alexander  1st Team In-Season Tournament All-Tournament
37           Damian Lillard  1st Team In-Season Tournament All-Tournament
38           Alperen Şengün  1st Team In-Season Tournament All-Tournament
39               Trae Young  1st Team In-Season Tournament All-Tournament
40    Giannis Antetokounmpo                                  NBA All-Star
41  Shai Gilgeous-Alexander                                  NBA All-Star
42             Nikola Jokić                                  NBA All-Star
43         Donovan Mitchell                                  NBA All-Star
44           Alperen Şengün                                  NBA All-Star
45            Pascal Siakam                                  NBA All-Star
46       Karl-Anthony Towns                                  NBA All-Star
47        Victor Wembanyama                                  NBA All-Star
48               Trae Young                                  NBA All-Star
49            Jalen Brunson                                  NBA All-Star
50          Cade Cunningham                                  NBA All-Star
51          Anthony Edwards                                  NBA All-Star
52           Darius Garland                                  NBA All-Star
53              Tyler Herro                                  NBA All-Star
54        Jaren Jackson Jr.                                  NBA All-Star
55              Evan Mobley                                  NBA All-Star
56           Jalen Williams                                  NBA All-Star
57             Jaylen Brown                                  NBA All-Star
58            Stephen Curry                                  NBA All-Star
59            Anthony Davis                                  NBA All-Star
60             Kevin Durant                                  NBA All-Star
61             James Harden                                  NBA All-Star
62             Kyrie Irving                                  NBA All-Star
63             LeBron James                                  NBA All-Star
64           Damian Lillard                                  NBA All-Star
65             Jayson Tatum                                  NBA All-Star